{
  pkgs,
  guardRole,
  ...
}:

guardRole "desktop" {
  # User applications
  home.packages = with pkgs; [
    kitty
    nautilus
  ];

  # niri configuration for DMS integration
  # Reference: https://danklinux.com/docs/dankmaterialshell/compositors
  # Note: DMS include files are generated by DMS when it runs.
  # Using "-" prefix for optional includes (niri ignores missing files with this prefix)
  xdg.configFile."niri/config.kdl".text = ''
    // Environment variables for Wayland
    environment {
      XDG_CURRENT_DESKTOP "niri"
      QT_QPA_PLATFORM "wayland"
      ELECTRON_OZONE_PLATFORM_HINT "auto"
      QT_QPA_PLATFORMTHEME "gtk3"
    }

    // Spawn kitty as terminal
    binds {
      Mod+Return { spawn "kitty"; }
    }

    // Layer rules for DMS wallpaper integration with niri overview
    layer-rule {
      match namespace="^quickshell"
      place-within-backdrop true
    }

    // DMS includes for theming, layout, and keybinds
    // Note: These files are generated by DMS. Using "-" prefix makes them optional.
    -include "dms/colors.kdl"
    -include "dms/layout.kdl"
    -include "dms/alttab.kdl"
    -include "dms/binds.kdl"
  '';

  # Systemd user service to bind DMS to niri session
  # This ensures DMS starts only with niri sessions
  systemd.user.services.dms-niri-binding = {
    Unit = {
      Description = "Bind DMS to niri session";
      After = [ "niri.service" ];
      BindsTo = [ "niri.service" ];
    };
    Install = {
      WantedBy = [ "niri.service" ];
    };
    Service = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.coreutils}/bin/true";
    };
  };
}
