{
  lib,
  hostName,
  ...
}:

lib.mkIf (hostName == "desktop") {
  # Bootloader (systemd-boot for UEFI systems)
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  # Placeholder for hardware-configuration
  # This should be replaced with actual hardware-configuration.nix contents
  # generated by nixos-generate-config on the target machine
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };
}
