{
  lib,
  hostName,
  ...
}:

lib.mkIf (hostName == "desktop") {
  # Bootloader (systemd-boot for UEFI systems)
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  # TODO: Replace with actual hardware-configuration.nix contents
  # generated by nixos-generate-config on the target machine.
  # Example:
  #   nixos-generate-config --show-hardware-config
  # Then update device labels/UUIDs below to match your disk layout.
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };
}
