# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  guardRole,
  ...
}:

guardRole "thinkpadE14" {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "thunderbolt"
      "nvme"
      "usb_storage"
      "usbhid"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelParams = [
      "mem_sleep_default=s2idle"
      "nvme.noacpi=1"
      "pcie_aspm=force"

      # "tpm_tis.interrupts=0"
      # "tpm.disable=1"
      # "i915.enable_dc=1"
      # "i915.enable_psr=1"
      # "pm_async=0"
      # "pci=noaer"
      # "modprobe.blacklist=ucsi_acpi,intel_vbtn,thunderbolt,tpm,tpm_tis,tpm_crb,tpm_tis_core"
    ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1285a5f5-e725-421a-a119-1a7ad156d113";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/19F1-B8A6";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  boot.resumeDevice = "/dev/disk/by-uuid/2853ed37-6fdb-4bd7-bd2e-840b7775ee15";
  swapDevices = [ { device = "/dev/disk/by-uuid/2853ed37-6fdb-4bd7-bd2e-840b7775ee15"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
