---
name: CI

"on": [push, pull_request, workflow_dispatch]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filter:
    name: Path filter
    runs-on: ubuntu-latest
    outputs:
      nvim: ${{ steps.filter.outputs.nvim }}
      nixos: ${{ steps.filter.outputs.nixos }}
      github_workflows: ${{ steps.filter.outputs.github_workflows }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            nvim:
              - 'nvim/**'
            nixos:
              - 'nixos-wsl/**'
            github_workflows:
              - '.github/workflows/**'
              - '.github/workflows/*.yml'
              - '.github/workflows/*.yaml'

  nixos-ci:
    name: "NixOS: fmt-check + lint + flake check"
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.nixos == 'true' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Run NixOS CI
        run: nix run ./nixos-wsl#apps.x86_64-linux.nixos-ci

  nixos-build:
    name: "NixOS: build toplevel"
    runs-on: ubuntu-latest
    needs: [filter, nixos-ci]
    if: ${{ needs.filter.outputs.nixos == 'true' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Show flake
        run: nix flake show ./nixos-wsl

      - name: Build NixOS toplevel
        run: |
          nix build \
            ./nixos-wsl#nixosConfigurations.nixos.config.system.build.toplevel \
            --print-build-logs \
            --no-link \
            -L

  nvim-ci:
    name: "Neovim: stylua --check"
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.nvim == 'true' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Run Neovim CI
        run: nix run ./nixos-wsl#apps.x86_64-linux.nvim-ci

  workflows-ci:
    name: "GitHub Workflows: actionlint + yamllint"
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.github_workflows == 'true' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Run Workflows CI
        run: nix run ./nixos-wsl#apps.x86_64-linux.workflows-ci
